# Generated by Django 5.2.1 on 2025-05-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agente',
            new_name='Corredor',
        ),
        migrations.RenameField(
            model_name='arriendo',
            old_name='agente',
            new_name='Corredor',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='agente',
            new_name='Corredor',
        ),
    ]
