# Generated by Django 5.2.1 on 2025-05-23 15:55

import django.db.models.deletion
import propiedades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('propiedades', '0004_alter_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_pics/'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to=propiedades.models.property_image_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
