# Generated by Django 5.2.1 on 2025-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_venta_imagen_principal_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatar'},
        ),
        migrations.AlterModelOptions(
            name='corredor',
            options={'verbose_name': 'Corredor', 'verbose_name_plural': 'Corredores'},
        ),
        migrations.AddField(
            model_name='arriendo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='arriendos/'),
        ),
        migrations.AddField(
            model_name='venta',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
