# Generated by Django 5.2.1 on 2025-05-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0005_venta_imagen_principal_imagen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avatar",
            options={"verbose_name": "Avatar", "verbose_name_plural": "Avatar"},
        ),
        migrations.AlterModelOptions(
            name="corredor",
            options={"verbose_name": "Corredor", "verbose_name_plural": "Corredores"},
        ),
    ]
