# Generated by Django 5.2.1 on 2025-05-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0006_alter_avatar_options_alter_corredor_options"),
        ("propiedades", "0006_alter_avatar_options_alter_corredor_options_and_more"),
    ]

    operations = []
