# Generated by Django 5.2.1 on 2025-05-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0007_arriendo_usuario_venta_usuario"),
        ("propiedades", "0007_merge_20250523_1554"),
    ]

    operations = []
