# Generated by Django 5.2.1 on 2025-06-01 17:55

import ckeditor_uploader.fields
import propiedades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_arriendo_fecha_publicacion_venta_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='img/default_avatar.png', upload_to=propiedades.models.avatar_upload_path),
        ),
    ]
