# Generated by Django 5.2.1 on 2025-06-01 21:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_arriendo_acepta_mascotas_arriendo_banios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Post')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='posts_pics/', verbose_name='Imagen Principal del Post')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post del Blog',
                'verbose_name_plural': 'Posts del Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
